"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['arducom.py']
DATA_FILES = ['gamepad_open.png',
 'gamepad_close.png',
 'gamepad_echo.png',
 'gamepad_write.png',
 'serial_open.png',
 'serial_close.png']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
